### ISSUE TITLE
Optimize API

### ISSUE THREAD

**Issue by sunxiaojian** [openmessaging/openconnect#41]
1. Add struct object model
统一struct构建方式，帮助快速完成struct的构建 

2. Optimize empty method
第一种：完全没必要实现的方法，需要隐掉
第二种：可实现，可不实现的方法，需要设置default，不应该出现即可以在 A方法同时也可以在B 方法中实现的逻辑，比如 init 和 validate

3. Add sourcerecord and sinkrecord
     source 中的position和offset 在sink端中是不需要的，如果在sink端消费record时，对api中字段的释义不明确，就会造成很多的社区沟通成本，这样也会显的api不是很专一，所以抽象的好处是能让开发者看到的字段和api都是能可解释的且都是有明确含义的；这样也会对未来sink和source对象的独立的功能扩展和开发带来便利

4. Add offset writer abstraction
包装RecordOffset使用使用，保证每个任务的offset的唯一性

..........

**Comment by odbozhou** [comment]
metged
